services:
  portfolio-optimization:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: portfolio-optimization-simulator

    ports:
      - "8501:8501"

    volumes:
      # Mount application source code
      - ./app:/app/app
      - ./src:/app/src
      - ./config:/app/config

      # Persist data
      - ./data:/app/data

    #env_file:
    #  - .env

    environment:
      PYTHONUNBUFFERED: "1"

    restart: unless-stopped

    command: >
      streamlit run app/Home.py
      --server.address=0.0.0.0
      --server.port=8501
      --server.headless=true
      --browser.gatherUsageStats=false